import {ACTIVE, MODES, STAGES, AUTO_RESUME_REASONS, AUTO_RETRY_LIMIT, AUTO_RETRY_DELAY, PHONE_OUTCOMES, autoRetryAllowed, defaultProfile, checkedProfile, newPassword, contentAllowed, publicJob, pageKind, recordEvent, diagnosticReport, oauthCallback, laterStage, pauseReason} from './shared.mjs';
import {MAILBOX} from './private-config.mjs';
import * as PRIVATE_CONFIG from './private-config.mjs';
import {RUN_TTL, startMailbox, pollMailbox} from './cloudflare.mjs';
import {hmeConfig} from './hme.mjs';
import {RUNNER_ALARM, createRunner, runnerConfig, runnerPauseFinal} from './runner.mjs';

// Server mode: only a per-run private-config.mjs generated by Team48 exports a valid RUNNER.
// Without it (every personal package) all code below behaves exactly as before.
const RUNNER = runnerConfig(PRIVATE_CONFIG.RUNNER);
let runner = null; // created at the end of this file when RUNNER is set
// Personal packages with a valid HME export read codes from iCloud via icloud-hme; server mode keeps Cloudflare.
const MAIL = (!RUNNER && hmeConfig(PRIVATE_CONFIG.HME || {})) || MAILBOX;
const MAIL_NAME = MAIL.kind === 'hme' ? 'iCloud' : 'Cloudflare';

// Optional Team48 handoff: sync the team, link the member, authorize, push and count.
const TEAM48 = (() => {
  try {
    const config = PRIVATE_CONFIG.TEAM48;
    const url = new URL(config.baseUrl);
    const local = url.protocol === 'http:' && ['127.0.0.1', 'localhost'].includes(url.hostname);
    return (url.protocol === 'https:' || local) && typeof config.token === 'string' && config.token.length >= 24 ?
      {origin: url.origin, token: config.token} : null;
  } catch { return null; }
})();
async function team48(path, body) {
  if (!TEAM48) throw new Error('插件未配置 Team48 地址和令牌，请用 --team48-token 重新打包。');
  let response;
  try {
    response = await fetch(TEAM48.origin + path, {
      method: body ? 'POST' : 'GET', credentials: 'omit', cache: 'no-store', signal: AbortSignal.timeout(90000),
      headers: {Authorization: `Bearer ${TEAM48.token}`, Accept: 'application/json', ...(body ? {'Content-Type': 'application/json'} : {})},
      body: body ? JSON.stringify(body) : undefined,
    });
  } catch { throw new Error('无法连接 Team48，请检查网络后重试。'); }
  if (response.status === 401) throw new Error('Team48 拒绝了插件令牌，请核对 EXTENSION_API_TOKEN 后重新打包。');
  if (response.status === 404) throw new Error('Team48 未启用插件接口，请在服务器配置 EXTENSION_API_TOKEN 并更新版本。');
  if (!response.ok) throw new Error(`Team48 返回 HTTP ${response.status}，请稍后重试。`);
  return response.json();
}

// ---- Phone relay: numbers and SMS codes come from Team48's phone pool (docs/contracts/phone-relay.md). ----
// Only for auto/review jobs of a package with a Team48 token, or server jobs whose task allowed the pool.
// The full number stays in the job and the page; status text shows its last 4 digits only.
const PHONE_TRIES = 3, SMS_WAIT = 90000, SMS_POLL = 5000;
const PHONE_REASONS = {invalid: '不被 OpenAI 接受', recently_used: '刚被用过', risk: '收不到短信或被切到 WhatsApp',
  no_sms: '90 秒内没收到短信', wrong_code: '短信验证码被拒', lease_lost: '已不在本任务名下', cancelled: '提交后页面没有反应'};
let phoneCalls = 0; // relay requests in flight; a new number is only requested when none is
const phoneRelayEnabled = job => !!job && !job.phoneRelayOff && ['auto', 'review'].includes(job.mode || 'auto') &&
  (RUNNER && job.runner ? job.runner.phonePool === true : !RUNNER && !!TEAM48);
const phoneContext = job => ({id: job.id, session: job.id.replace(/-/g, '').toLowerCase(), email: job.email,
  workspaceId: Number(job.autoHandoff?.workspaceId || job.handoff?.workspaceId) || 0, phase: job.phase === 'oauth' ? 'oauth' : 'signup'});
// Server text for the status line: never a link or a long digit run.
const relayText = value => String(value || '').replace(/https?:\/\/\S+/g, '[链接]').replace(/\+?\d[\d\s()-]{6,}\d/g, '***').slice(0, 150);
async function phoneRelay(context, body) {
  const payload = {...body, phase: context.phase};
  if (RUNNER) return runner ? runner.phone(payload) : {ok: false, network: true, message: '服务器模式尚未就绪。'};
  if (!TEAM48) return {ok: false, error_code: 'phone_relay_disabled', message: '插件未配置 Team48 令牌。'};
  Object.assign(payload, {session: context.session, email: context.email, ...(context.workspaceId > 0 ? {workspaceId: context.workspaceId} : {})});
  let response;
  try {
    response = await fetch(TEAM48.origin + '/api/ext/phone', {
      method: 'POST', credentials: 'omit', cache: 'no-store', signal: AbortSignal.timeout(30000),
      headers: {Authorization: `Bearer ${TEAM48.token}`, Accept: 'application/json', 'Content-Type': 'application/json'},
      body: JSON.stringify(payload),
    });
  } catch { return {ok: false, network: true, message: '无法连接 Team48 接码接口。'}; }
  if (response.status >= 500) return {ok: false, network: true, message: `Team48 接码接口返回 HTTP ${response.status}。`};
  let data = null;
  try { data = await response.json(); } catch { /* not JSON */ }
  if (response.ok && data && typeof data === 'object' && typeof data.ok === 'boolean') return data;
  const message = response.status === 401 ? 'Team48 拒绝了插件令牌，请核对后重新打包。' :
    response.status === 404 ? 'Team48 未启用接码接口，请更新服务器版本。' : `Team48 接码接口返回 HTTP ${response.status}。`;
  return {ok: false, error_code: 'invalid_request', message};
}
// report / release: the result is ignored (the server lock expires by itself).
function firePhoneCall(context, body) {
  phoneCalls++;
  phoneRelay(context, body).catch(() => {}).finally(() => { phoneCalls = Math.max(0, phoneCalls - 1); });
}
function resetPhoneSteps(job) {
  // Every number is a fresh submission of the same page: drop the old claims for the phone steps.
  for (const bag of [job.claims, job.continueClicks, job.clickReservations, job.reviewSteps]) {
    for (const key of Object.keys(bag || {})) if (/^phone(_otp)?:/.test(key)) delete bag[key];
  }
  if (job.attempts) { delete job.attempts.phone; delete job.attempts.phone_otp; }
  if (/^phone(_otp)?:/.test(job.retryClaim || '')) delete job.retryClaim;
}
const phoneLimit = job => job.phoneLimit || PHONE_TRIES;
function phoneLimitPause(job) {
  pauseJob(job, `已连续 ${job.phoneTries || 0} 个号失败，可能是账号或代理被风控，请人工处理。`, 'phone_limit');
}
// Drops the current number after a failure: report it (unless the lease is already gone), then go back and
// take the next one, or pause once the tries are used up.
function failPhone(job, outcome) {
  const phone = job.phone;
  if (!phone) return;
  const context = phoneContext(job);
  delete job.phone;
  resetPhoneSteps(job);
  if (!phone.bound && outcome !== 'lease_lost') (job.phoneFailedIds ||= []).push(phone.id);
  job.phoneBack = true;
  recordEvent(job, 'phone_rejected', {stage: job.stage, outcome: PHONE_OUTCOMES.has(outcome) ? outcome : undefined});
  if (outcome !== 'lease_lost') firePhoneCall(context, {action: 'report', phoneId: phone.id, bound: phone.bound, outcome});
  if (phone.bound) {
    // The account's own number cannot be swapped for another one.
    delete job.phoneBack;
    pauseJob(job, `账号已绑定的尾号 ${phone.tail} 号码${PHONE_REASONS[outcome] || '不可用'}，请人工处理后点继续。`, 'phone_relay_error');
    return;
  }
  if ((job.phoneTries || 0) >= phoneLimit(job)) { phoneLimitPause(job); return; }
  job.message = `尾号 ${phone.tail} 的号码${PHONE_REASONS[outcome] || '不可用'}，正在换号（已用 ${job.phoneTries || 0}/${phoneLimit(job)} 个）`;
}
// The page left the phone steps after the SMS code was submitted.
function phoneSucceeded(job) {
  const phone = job.phone;
  if (!phone?.code && !phone?.codeSubmittedAt) return false;
  const context = phoneContext(job);
  delete job.phone; delete job.phoneBack;
  resetPhoneSteps(job);
  job.phoneSuccess = true;
  firePhoneCall(context, {action: 'report', phoneId: phone.id, bound: phone.bound, outcome: 'success'});
  return true;
}
// Stop, timeout or closed tab: free the number at once instead of waiting for the lock to expire.
function releasePhone(job) {
  delete job.phoneBack;
  if (!job.phone) return;
  const context = phoneContext(job);
  delete job.phone;
  if (!RUNNER) firePhoneCall(context, {action: 'release'}); // the server releases a run's numbers itself
}
const phoneReply = phone => ({id: phone.id, number: phone.number, national: phone.number.replace(/\D/g, '').slice(-10), tail: phone.tail, bound: phone.bound});
// Runs outside the job queue (like finishCodePoll); only the result is stored under it.
async function finishPhoneCall(call) {
  let result;
  try {
    const body = call.action === 'acquire' ? {action: 'acquire', bound: call.bound} : {action: 'code', phoneId: call.phoneId, bound: call.bound};
    for (let attempt = 0; ; attempt++) {
      result = await phoneRelay(call, body);
      if (call.action !== 'acquire' || !result?.network || attempt >= 2) break;
      await sleep(3000);
    }
    // A report that never reached the server leaves the failed number locked to this session.
    if (call.action === 'acquire' && !call.bound && result?.ok && call.failedIds.includes(Number(result.phoneId))) {
      await phoneRelay(call, {action: 'release'});
      result = await phoneRelay(call, body);
      if (result?.ok && call.failedIds.includes(Number(result.phoneId))) {
        // The pool has nothing this account has not tried yet.
        await phoneRelay(call, {action: 'release'});
        result = {ok: false, error_code: 'phone_pool_empty', message: '号码池里没有本账号还没试过的号。'};
      }
    }
  } catch { result = {ok: false, network: true, message: '接码请求失败。'}; }
  finally { phoneCalls = Math.max(0, phoneCalls - 1); }
  return serial(async () => {
    const job = await loadJob();
    if (!job || job.id !== call.id) return {};
    return call.action === 'acquire' ? applyAcquire(job, call, result) : applyCode(job, call, result);
  });
}
async function applyAcquire(job, call, result) {
  const number = String(result?.number || '');
  if (result?.ok && (call.bound ? /^\+?\d{6,15}$/.test(number) : /^\+1\d{10}$/.test(number)) && Number.isInteger(Number(result.phoneId))) {
    const phone = {id: Number(result.phoneId), number, bound: call.bound, tail: number.slice(-4), acquiredAt: Date.now(),
      submittedAt: call.bound ? Date.now() : 0, codeSubmittedAt: 0, lastPoll: 0};
    if (!ACTIVE.has(job.status)) {
      firePhoneCall(call, {action: 'report', phoneId: phone.id, bound: phone.bound, outcome: 'cancelled'});
      return {};
    }
    if (job.phone && job.phone.id !== phone.id) {
      firePhoneCall(call, {action: 'report', phoneId: job.phone.id, bound: job.phone.bound, outcome: 'cancelled'});
    }
    job.phone = phone;
    job.phoneTries = (job.phoneTries || 0) + 1;
    resetPhoneSteps(job);
    recordEvent(job, 'phone_acquired', {stage: job.stage});
    job.message = call.bound ? `页面要求验证已绑定的尾号 ${phone.tail} 号码，等待短信验证码` :
      `已领取尾号 ${phone.tail} 的号码，正在填写（第 ${job.phoneTries}/${phoneLimit(job)} 个）`;
    await saveJob(job);
    return job.status === 'running' ? phoneReply(phone) : {};
  }
  if (result?.ok) {
    // Not a +1 number: the page could not take it as is.
    firePhoneCall(call, {action: 'report', phoneId: Number(result.phoneId) || 0, bound: call.bound, outcome: 'cancelled'});
    result = {ok: false, message: '服务器下发的号码不是 +1 美国号。'};
  }
  if (job.status !== 'running' || result?.error_code === 'run_gone') return {};
  const code = result?.error_code;
  if (code === 'phone_pool_empty') pauseJob(job, '号码池没有可用号，去 Team48 资源页导入后点继续。', 'phone_pool_empty');
  else if (code === 'phone_relay_disabled') {
    // Same as a package without relay: stop at the phone page like before.
    job.phoneRelayOff = true;
    pauseJob(job, job.phase === 'oauth' ? '授权要求手机验证，请在网页手动完成；完成后插件会自动提交回调。' : '注册需要手机验证，请在网页手动完成后继续。', 'phone');
  } else pauseJob(job, `接码失败：${relayText(result?.message) || '服务器没有返回号码'}。请处理后点继续。`, 'phone_relay_error');
  await saveJob(job);
  return {paused: true};
}
async function applyCode(job, call, result) {
  const phone = job.phone;
  if (!ACTIVE.has(job.status) || phone?.id !== call.phoneId || phone.bound !== call.bound) return {code: null};
  if (result?.ok === false && result.error_code === 'lease_lost') {
    // While paused, the next poll after Continue gets the same answer.
    if (job.status !== 'running') return {code: null};
    failPhone(job, 'lease_lost');
    await saveJob(job);
    return {rejected: true};
  }
  const code = result?.ok ? String(result.code || '') : '';
  if (!/^\d{6}$/.test(code) || phone.codeSubmittedAt) return {code: null};
  if (!phone.code) {
    phone.code = code;
    recordEvent(job, 'sms_received', {stage: 'phone_otp'});
    if (job.status === 'running') job.message = '已收到短信验证码，正在逐位输入';
    await saveJob(job);
  }
  return job.status === 'running' ? {code: phone.code} : {code: null};
}

const ready = Promise.all([
  chrome.storage.local.remove('config'),
  chrome.storage.session.setAccessLevel({accessLevel: 'TRUSTED_CONTEXTS'}),
]);
let queue = Promise.resolve();
const serial = task => {
  const next = queue.then(task);
  queue = next.catch(() => {});
  return next;
};
const saveJob = async job => {
  await chrome.storage.session.set({job});
  if (RUNNER && job.runner) runner?.jobSaved();
  if (['done', 'stopped'].includes(job.status)) void releaseDebugger(job.tabId);
  const text = {running: '…', paused: '!', done: '✓', stopped: ''}[job.status] || '';
  try {
    await chrome.action.setBadgeText({tabId: job.tabId, text});
    await chrome.action.setBadgeBackgroundColor({tabId: job.tabId, color: job.status === 'paused' ? '#b36b19' : '#166a59'});
    await chrome.action.setTitle({tabId: job.tabId, title: `注册助手 · ${job.message}`});
  } catch { /* tab may have closed */ }
  return job;
};

// Trusted input: the browser itself generates mouse/keyboard events through CDP,
// so the page sees isTrusted=true and a normal keydown/keypress/input/keyup chain.
const debuggerTabs = new Set();
const pointers = new Map();
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
const between = (min, max) => min + Math.floor(Math.random() * (max - min + 1));
const cdp = async (tabId, method, params = {}) => {
  // Pause/stop can arrive while a pointer path or key hold is waiting. Only release
  // already-pressed inputs afterward; never start another move, press or insertion.
  const releasing = params.type === 'keyUp' || params.type === 'mouseReleased';
  if (method.startsWith('Input.') && !releasing) {
    const job = await loadJob();
    if (!job || job.tabId !== tabId || job.status !== 'running' || Date.now() >= job.expiresAt) throw new Error('任务已暂停、停止或超时。');
  }
  return chrome.debugger.sendCommand({tabId}, method, params);
};
async function attachDebugger(tabId, refreshFocus = false) {
  if (!chrome.debugger) throw new Error('浏览器未授予调试权限。');
  let fresh = false;
  if (!debuggerTabs.has(tabId)) {
    try { await chrome.debugger.attach({tabId}, '1.3'); }
    catch (error) {
      // A restarted worker loses its memory of an attachment it still owns.
      if (!/already attached/i.test(error.message)) throw error;
    }
    debuggerTabs.add(tabId); fresh = true;
  }
  // Pages in a background window still believe they have focus. Set once per attach and
  // once per page load (input-ready), not before every key.
  if (fresh || refreshFocus) await cdp(tabId, 'Emulation.setFocusEmulationEnabled', {enabled: true});
}
async function releaseDebugger(tabId) {
  if (!debuggerTabs.delete(tabId)) return;
  pointers.delete(tabId);
  try { await chrome.debugger.detach({tabId}); } catch { /* tab closed or already detached */ }
}
const KEYS = {' ': ['Space', 32], '-': ['Minus', 189], '=': ['Equal', 187], '[': ['BracketLeft', 219], ']': ['BracketRight', 221],
  '\\': ['Backslash', 220], ';': ['Semicolon', 186], "'": ['Quote', 222], ',': ['Comma', 188], '.': ['Period', 190], '/': ['Slash', 191], '`': ['Backquote', 192]};
const SHIFTED = {'!': '1', '@': '2', '#': '3', '$': '4', '%': '5', '^': '6', '&': '7', '*': '8', '(': '9', ')': '0',
  '_': '-', '+': '=', '{': '[', '}': ']', '|': '\\', ':': ';', '"': "'", '<': ',', '>': '.', '?': '/', '~': '`'};
const SPECIAL_KEYS = {Backspace: 8, Tab: 9, Enter: 13, Escape: 27, Home: 36, End: 35, ArrowLeft: 37, ArrowUp: 38, ArrowRight: 39, ArrowDown: 40};
function keyFor(character) {
  const base = SHIFTED[character] || character.toLowerCase();
  const shift = !!SHIFTED[character] || /[A-Z]/.test(character);
  if (/^[a-z]$/.test(base)) return {code: `Key${base.toUpperCase()}`, keyCode: base.toUpperCase().charCodeAt(0), shift};
  if (/^[0-9]$/.test(base)) return {code: `Digit${base}`, keyCode: base.charCodeAt(0), shift};
  return KEYS[base] ? {code: KEYS[base][0], keyCode: KEYS[base][1], shift} : null;
}
async function typeKey(tabId, key) {
  const special = SPECIAL_KEYS[key];
  if (special) {
    const event = {key, code: key, windowsVirtualKeyCode: special, nativeVirtualKeyCode: special};
    // Enter needs its text so the page performs implicit form submission.
    await cdp(tabId, 'Input.dispatchKeyEvent', key === 'Enter' ? {type: 'keyDown', text: '\r', unmodifiedText: '\r', ...event} : {type: 'rawKeyDown', ...event});
    await sleep(between(30, 70));
    await cdp(tabId, 'Input.dispatchKeyEvent', {type: 'keyUp', ...event});
    return;
  }
  const info = keyFor(key);
  if (!info) { await cdp(tabId, 'Input.insertText', {text: key}); return; }
  const shift = {key: 'Shift', code: 'ShiftLeft', windowsVirtualKeyCode: 16, nativeVirtualKeyCode: 16, location: 1};
  const modifiers = info.shift ? 8 : 0;
  let shiftPressed = false;
  try {
    if (info.shift) {
      await cdp(tabId, 'Input.dispatchKeyEvent', {type: 'rawKeyDown', modifiers, ...shift});
      shiftPressed = true;
      await sleep(between(25, 60));
    }
    const event = {key, code: info.code, windowsVirtualKeyCode: info.keyCode, nativeVirtualKeyCode: info.keyCode, modifiers};
    await cdp(tabId, 'Input.dispatchKeyEvent', {type: 'keyDown', text: key, unmodifiedText: key, ...event});
    try { await sleep(between(35, 95)); }
    finally { await cdp(tabId, 'Input.dispatchKeyEvent', {type: 'keyUp', ...event}); }
  } finally {
    if (shiftPressed) await cdp(tabId, 'Input.dispatchKeyEvent', {type: 'keyUp', ...shift, modifiers: 0});
  }
}
async function moveMouse(tabId, x, y) {
  // An eased, slightly curved path from the last position instead of a jump.
  const from = pointers.get(tabId) || {x: x + between(-160, 160), y: y + between(80, 220)};
  const distance = Math.hypot(x - from.x, y - from.y);
  if (distance < 1) { pointers.set(tabId, {x, y}); return; }
  const steps = Math.max(4, Math.min(28, Math.round(distance / 22)));
  const bend = between(-1, 1) * Math.min(40, distance / 6);
  for (let step = 1; step <= steps; step++) {
    const t = step / steps, eased = t * t * (3 - 2 * t), arc = Math.sin(Math.PI * t) * bend;
    const px = from.x + (x - from.x) * eased - (y - from.y) / (distance || 1) * arc;
    const py = from.y + (y - from.y) * eased + (x - from.x) / (distance || 1) * arc;
    await cdp(tabId, 'Input.dispatchMouseEvent', {type: 'mouseMoved', x: step === steps ? x : px, y: step === steps ? y : py, pointerType: 'mouse'});
    await sleep(between(6, 18));
  }
  pointers.set(tabId, {x, y});
}
async function inputMessage(message, sender) {
  const job = await loadJob();
  if (!job || !contentAllowed(sender, job, !RUNNER) || message.jobId !== job.id || job.status !== 'running' ||
      message.version !== chrome.runtime.getManifest().version || Date.now() >= job.expiresAt ||
      job.mode === 'manual') return {active: false};
  if (['input-text', 'input-key'].includes(message.type) && job.mode === 'submit' && message.key !== 'Enter') return {active: false};
  const tabId = sender.tab.id;
  if (message.type === 'input-ready') {
    try { await attachDebugger(tabId, true); }
    catch { job.inputMode = 'synthetic'; await chrome.storage.session.set({job}); return {trusted: false}; }
    job.inputMode = 'cdp'; await chrome.storage.session.set({job});
    return {trusted: true};
  }
  await attachDebugger(tabId);
  const x = Number(message.x), y = Number(message.y);
  const point = Number.isFinite(x) && Number.isFinite(y) && x >= 0 && y >= 0 && x < 20000 && y < 20000;
  if (message.type === 'input-date-layout' && Number.isInteger(message.index) && message.index >= 0) {
    const {root} = await cdp(tabId, 'DOM.getDocument', {depth: 0});
    const {nodeIds} = await cdp(tabId, 'DOM.querySelectorAll', {nodeId: root.nodeId, selector: 'input[type="date"]'});
    if (!nodeIds[message.index]) throw new Error('日期控件已变化。');
    const {node} = await cdp(tabId, 'DOM.describeNode', {nodeId: nodeIds[message.index], depth: -1, pierce: true});
    const parts = [];
    const visit = item => {
      const attrs = item.attributes || [];
      const at = attrs.indexOf('pseudo');
      const match = at >= 0 && /^-webkit-datetime-edit-(year|month|day)-field$/.exec(attrs[at + 1]);
      if (match) parts.push(match[1]);
      for (const child of [...(item.children || []), ...(item.shadowRoots || [])]) visit(child);
    };
    visit(node);
    if (parts.length !== 3 || new Set(parts).size !== 3) throw new Error('无法识别日期分段，请手动填写后继续。');
    return {parts};
  }
  if (message.type === 'input-move' && point) { await moveMouse(tabId, x, y); return {}; }
  if (message.type === 'input-click' && point) {
    await moveMouse(tabId, x, y);
    const button = {x, y, button: 'left', clickCount: 1, pointerType: 'mouse'};
    await cdp(tabId, 'Input.dispatchMouseEvent', {type: 'mousePressed', buttons: 1, ...button});
    await sleep(between(50, 110));
    await cdp(tabId, 'Input.dispatchMouseEvent', {type: 'mouseReleased', buttons: 0, ...button});
    return {sent: true};
  }
  if (message.type === 'input-key' && typeof message.key === 'string' && (Object.hasOwn(SPECIAL_KEYS, message.key) || [...message.key].length === 1)) {
    await typeKey(tabId, message.key);
    return {sent: true};
  }
  if (message.type === 'input-text' && typeof message.text === 'string' && message.text.length > 0 && message.text.length <= 256) {
    // One insertion, like a password manager or paste, instead of hand-typing a long random secret.
    await cdp(tabId, 'Input.insertText', {text: message.text});
    return {sent: true};
  }
  if (message.type === 'input-wheel' && point && [message.deltaY, message.deltaX ?? 0].every(value => Number.isFinite(Number(value)) && Math.abs(Number(value)) <= 600)) {
    await cdp(tabId, 'Input.dispatchMouseEvent', {type: 'mouseWheel', x, y, deltaX: Number(message.deltaX || 0), deltaY: Number(message.deltaY), pointerType: 'mouse'});
    pointers.set(tabId, {x, y});
    return {};
  }
  if (message.type === 'input-drift') {
    const width = Number(message.width), height = Number(message.height);
    // Idle movement is optional: an odd viewport (loading, tiny or spoofed window) skips it instead of pausing the run.
    if (!(width >= 80 && height >= 80 && width < 20000 && height < 20000)) return {};
    // A small idle movement from wherever the pointer rests.
    const from = pointers.get(tabId) || {x: width * (0.3 + Math.random() * 0.4), y: height * (0.3 + Math.random() * 0.4)};
    const clamp = (value, max) => Math.min(max - 20, Math.max(20, value));
    await moveMouse(tabId, clamp(from.x + between(-140, 140), width), clamp(from.y + between(-90, 90), height));
    return {};
  }
  throw new Error(`输入指令无效（${String(message.type).slice(0, 30)}）。`);
}
const loadJob = async () => (await chrome.storage.session.get('job')).job;
async function expire(job) {
  if (job && ACTIVE.has(job.status) && Date.now() >= job.expiresAt) {
    job.status = 'stopped'; job.message = job.phase === 'oauth' ? '本次授权已超时，可重新接入。' : '本次注册已超时，请重新开始。';
    recordEvent(job, 'expired');
    delete job.baseline; delete job.pendingCode;
    releasePhone(job);
    if (job.handoff?.status === 'authorizing') failHandoff(job, '授权超时，可选择团队后重新接入。');
    await saveJob(job);
  }
  return job;
}

// ---- Team48 handoff: sync -> link -> OAuth in this tab -> callback -> push + count ----
// Handoff statuses: (resolving ->) syncing -> (waiting_join ->) opening -> authorizing -> completing -> done,
// or failed / callback_retry. Everything except the page steps runs here in the worker.
const HANDOFF_ACTIVE = new Set(['resolving', 'syncing', 'waiting_join', 'opening', 'completing']);
const JOIN_WAIT = 3 * 60 * 1000, JOIN_RETRY = 10000, SYNC_LIMIT = 4 * 60 * 1000;
const patchJob = (id, change) => serial(async () => {
  const job = await loadJob();
  if (!job || job.id !== id) return null;
  change(job);
  await saveJob(job);
  return job;
});
function failHandoff(job, message, code) {
  if (!job.handoff) return;
  job.handoff.status = 'failed';
  job.handoff.message = String(message || '接入失败').slice(0, 300);
  if (code) job.handoff.errorCode = String(code).slice(0, 60);
  delete job.handoff.ticket; delete job.handoff.authorizeUrl; delete job.handoff.callbackUrl;
  // Server mode: a failed authorization ends the task; the server reads the stopped report.
  if (job.runner && job.status !== 'stopped') { job.status = 'stopped'; job.message = job.handoff.message; }
}
function beginHandoff(job, workspaceId, workspaceName) {
  job.handoff = {status: 'syncing', workspaceId, workspaceName: String(workspaceName || '').slice(0, 120),
    startedAt: Date.now(), message: '正在同步团队成员…'};
}
// ---- Automatic team: Team48 checks every team's live members and invites for this email. ----
// The lookup starts with the signup, so its few seconds per team are normally over by the end.
const resolveTasks = new Map();
function resolveTeam({id, email}, {fresh = false} = {}) {
  if (fresh || !resolveTasks.has(id)) {
    resolveTasks.clear();
    resolveTasks.set(id, team48('/api/ext/resolve', {email})
      .catch(error => ({ok: false, state: 'failed', error_code: 'network', message: error.message})));
  }
  return resolveTasks.get(id);
}
function applyResolved(job, result) {
  const auto = job.autoHandoff;
  if (!auto?.auto) return false;
  const id = Number(result?.workspace?.id);
  if (result?.ok && Number.isInteger(id) && id > 0) {
    auto.workspaceId = id;
    auto.workspaceName = String(result.workspace.name || `团队 ${id}`).slice(0, 120);
    auto.resolve = {status: 'found', message: `已识别团队：${auto.workspaceName}`};
    return true;
  }
  auto.resolve = {status: result?.state === 'ambiguous' ? 'ambiguous' : 'failed',
    message: String(result?.message || '未识别到团队').slice(0, 200)};
  return false;
}
function prefetchTeam({id, email}) {
  resolveTeam({id, email}).then(result => patchJob(id, current => {
    if (current.autoHandoff?.resolve?.status === 'resolving') applyResolved(current, result);
  })).catch(() => {});
}
async function resolveForHandoff(job) {
  let result = await resolveTeam(job);
  // A miss may predate the invitation or a flaky team read; check once more, fresh.
  if (!result?.ok && result?.state !== 'ambiguous' && result?.error_code !== 'owner_account') {
    result = await resolveTeam(job, {fresh: true});
  }
  await patchJob(job.id, current => {
    if (current.handoff?.status !== 'resolving') return;
    if (applyResolved(current, result)) {
      beginHandoff(current, current.autoHandoff.workspaceId, current.autoHandoff.workspaceName);
      return;
    }
    failHandoff(current, `${current.autoHandoff?.resolve?.message || '未识别到团队'}。请在下方选择团队后点「重新接入」。`,
      result?.error_code);
  });
}

let handoffTask = null;
function ensureHandoff() {
  // incognito: split shares session storage with the regular profile's worker, which cannot
  // see incognito tabs. Only the incognito worker may drive the handoff.
  // Server mode has no Team48 handoff: its runner.mjs submits the callback instead.
  if (RUNNER) return null;
  if (!chrome.extension.inIncognitoContext) return null;
  if (!handoffTask) {
    // Service workers can be suspended; the alarm resumes an interrupted handoff.
    void chrome.alarms.create('handoff-watchdog', {periodInMinutes: 0.5});
    handoffTask = runHandoff().catch(() => {}).finally(() => { handoffTask = null; });
  }
  return handoffTask;
}
function applyHandoff(job, result) {
  const handoff = job.handoff;
  if (handoff?.status !== 'syncing') return;
  if (result?.ok && result.state === 'syncing' && result.operation_id) {
    handoff.syncOperationId = String(result.operation_id); handoff.message = '正在同步团队成员…';
    return;
  }
  if (result?.state === 'not_joined') {
    // Give the user time to accept the invitation in the page; the check repeats.
    handoff.joinDeadline ||= Date.now() + JOIN_WAIT;
    if (Date.now() < handoff.joinDeadline) {
      Object.assign(handoff, {status: 'waiting_join', retryAt: Date.now() + JOIN_RETRY,
        message: '团队中仍是「已邀请」：请在网页接受邀请，插件每 10 秒重新同步检查（最多 3 分钟）。'});
      delete handoff.syncOperationId;
      return;
    }
  }
  if (result?.ok && result.state === 'authorize' && result.ticket && result.account_id) {
    let url;
    try { url = new URL(result.authorize_url); } catch { url = null; }
    if (url?.origin !== 'https://auth.openai.com') return failHandoff(job, 'Team48 返回的授权链接无效。');
    Object.assign(handoff, {status: 'opening', accountId: Number(result.account_id), ticket: String(result.ticket),
      authorizeUrl: url.href, message: '已接入本地，正在打开授权页面',
      workspaceNames: (result.workspace?.names || [handoff.workspaceName]).map(String).filter(Boolean).slice(0, 5)});
    if (result.workspace?.name) handoff.workspaceName = String(result.workspace.name).slice(0, 120);
    return;
  }
  failHandoff(job, result?.message || 'Team48 未返回授权链接。', result?.error_code);
}
async function runHandoff() {
  for (let guard = 0; guard < 400; guard++) {
    const job = await serial(loadJob);
    const handoff = job?.handoff;
    if (!handoff || !HANDOFF_ACTIVE.has(handoff.status)) { await chrome.alarms.clear('handoff-watchdog'); return; }
    if (handoff.status === 'resolving') { await resolveForHandoff(job); continue; }
    if (handoff.status === 'opening') { await openAuthorization(job.id); continue; }
    if (handoff.status === 'completing') { await completeAuthorization(job.id); continue; }
    if (handoff.status === 'waiting_join') {
      if (Date.now() < handoff.retryAt) { await sleep(Math.min(2000, handoff.retryAt - Date.now())); continue; }
      await patchJob(job.id, current => {
        if (current.handoff?.status === 'waiting_join') { current.handoff.status = 'syncing'; current.handoff.message = '正在重新同步团队成员…'; }
      });
      continue;
    }
    if (Date.now() - handoff.startedAt > SYNC_LIMIT + JOIN_WAIT) {
      await patchJob(job.id, current => failHandoff(current, '团队同步超时，请到控制台检查母号授权后重试。'));
      continue;
    }
    let result;
    try {
      result = await team48('/api/ext/handoff', {email: job.email, workspace_id: handoff.workspaceId,
        ...(handoff.syncOperationId ? {sync_operation_id: handoff.syncOperationId} : {}),
        // Lets Team48 store the number that passed OpenAI's phone check on this account.
        ...(job.phoneSuccess ? {phone_session: phoneContext(job).session} : {})});
    } catch (error) {
      await patchJob(job.id, current => { if (current.handoff?.status === 'syncing') failHandoff(current, error.message); });
      continue;
    }
    await patchJob(job.id, current => applyHandoff(current, result));
    if (result?.state === 'syncing') await sleep(2000);
  }
}
async function openAuthorization(id) {
  const job = await serial(loadJob);
  if (job?.id !== id || job.handoff?.status !== 'opening') return;
  const fail = message => patchJob(id, current => { if (current.handoff?.status === 'opening') failHandoff(current, message); });
  let baseline = null;
  if (['auto', 'review'].includes(job.mode)) {
    // Snapshot the inbox first so only a fresh login code is ever used.
    try { baseline = await startMailbox(MAIL, job.email); }
    catch (error) { await fail(`读取邮箱失败：${error.message}`); return; }
  }
  let tabId = job.tabId;
  try { await chrome.tabs.get(tabId); }
  catch {
    try {
      if (RUNNER && job.runner) tabId = (await pickRunnerTab()).id;
      else {
        const window = await chrome.windows.getLastFocused();
        if (!window.incognito) throw new Error('not incognito');
        tabId = (await chrome.tabs.create({windowId: window.id, url: 'about:blank', active: true})).id;
      }
    } catch { await fail('注册标签页已关闭，请在无痕窗口中打开插件后重新接入。'); return; }
  }
  const ready = await patchJob(id, current => {
    if (current.handoff?.status !== 'opening') return;
    // A fresh page run: the signup submission records must not limit authorization steps.
    Object.assign(current, {tabId, phase: 'oauth', status: 'running', stage: 'signup', message: '正在打开授权页面',
      claims: {}, attempts: {}, continueClicks: {}, continueRetries: {}, clickReservations: {}, reviewSteps: {},
      baseline, lastPoll: 0, ignoredCodes: current.ignoredCodes || [], entryFormSeen: true, entryFallbackUsed: true,
      expiresAt: Date.now() + (current.mode === 'auto' ? RUN_TTL : 30 * 60 * 1000)});
    delete current.retryClaim; delete current.pendingCode; delete current.codeWaitSince;
    current.handoff.status = 'authorizing';
    current.handoff.message = '正在授权；拿到回调后自动提交 Team48';
    recordEvent(current, 'oauth_started');
  });
  if (ready?.handoff?.status !== 'authorizing') return;
  await chrome.alarms.create('signup-expiry', {when: ready.expiresAt});
  try { await chrome.tabs.update(tabId, {url: ready.handoff.authorizeUrl, active: true}); }
  catch {
    await patchJob(id, current => {
      current.status = 'stopped'; current.message = '授权标签页已关闭。';
      failHandoff(current, '授权标签页已关闭，可重新接入。');
    });
  }
}
async function completeAuthorization(id) {
  const job = await serial(loadJob);
  const handoff = job?.handoff;
  if (job?.id !== id || handoff?.status !== 'completing') return;
  if (!handoff.callbackUrl || !handoff.ticket) {
    await patchJob(id, current => failHandoff(current, '授权回调已丢失，请重新接入。'));
    return;
  }
  let result;
  try {
    result = await team48('/api/ext/handoff/complete', {account_id: handoff.accountId, workspace_id: handoff.workspaceId,
      ticket: handoff.ticket, callback_url: handoff.callbackUrl, push_sub2api: true, count_switch: true});
  } catch (error) {
    await patchJob(id, current => {
      if (current.handoff?.status !== 'completing') return;
      current.handoff.status = 'callback_retry';
      current.handoff.message = `${error.message} 回调已保留，可点击「重新提交回调」。`;
    });
    return;
  }
  await patchJob(id, current => {
    if (current.handoff?.status !== 'completing') return;
    if (!result?.ok) {
      const consumed = result?.error_code === 'callback_consumed';
      failHandoff(current, consumed ? '回调已提交过一次；请到控制台确认该账号的授权状态。' : result?.message || '授权失败。', result?.error_code);
      return;
    }
    Object.assign(current.handoff, {status: 'done', message: String(result.message || '授权完成'), followups: result.followups || {}});
    delete current.handoff.ticket; delete current.handoff.authorizeUrl; delete current.handoff.callbackUrl;
    if (current.codexResult !== 'phone_required') current.codexResult = 'no_phone';
    current.message = '已完成授权并提交 Team48。';
  });
}
function captureCallback(tabId, url) {
  if (!oauthCallback(url)) return;
  serial(async () => {
    const job = await loadJob();
    if (!job || job.tabId !== tabId || job.phase !== 'oauth' || job.handoff?.status !== 'authorizing') return false;
    const server = !!RUNNER && !!job.runner;
    const text = server ? '已拿到授权回调，正在提交服务器' : '已拿到授权回调，正在提交 Team48';
    Object.assign(job.handoff, {status: 'completing', callbackUrl: url, message: text});
    job.status = 'done'; job.stage = 'consent'; job.message = text;
    delete job.baseline; delete job.pendingCode;
    if (!phoneSucceeded(job)) releasePhone(job);
    recordEvent(job, 'oauth_callback');
    await saveJob(job);
    return server ? 'runner' : true;
  }).then(captured => {
    if (!captured) return;
    if (captured === 'runner') {
      // Server mode: runner.mjs posts the callback to the server instead of /api/ext/handoff/complete.
      runner?.submitCallback();
      chrome.tabs.update(tabId, {url: 'about:blank'}).catch(() => {});
      return;
    }
    ensureHandoff();
    // Replace the unreachable localhost page with the progress view.
    chrome.tabs.update(tabId, {url: chrome.runtime.getURL('popup.html')}).catch(() => {});
  }).catch(() => {});
}

// Signup is finished: stop the page runner and, if chosen, start the Team48 handoff.
function finishSignup(job, verified, event) {
  job.emailVerified = typeof verified === 'boolean' ? verified : null;
  recordEvent(job, event, {verified: job.emailVerified});
  job.status = 'done';
  job.message = event === 'manual_complete' ? '你已确认注册完成；Team48 授权时仍会核对登录邮箱。' :
    '已确认目标邮箱登录 ChatGPT；后续 Codex 验证要求需在授权时确认。';
  delete job.baseline; delete job.pendingCode; delete job.retryClaim;
  if (!phoneSucceeded(job)) releasePhone(job);
  const auto = job.autoHandoff;
  if (!auto || !TEAM48 || job.handoff) return;
  if (!auto.auto || auto.resolve?.status === 'found') beginHandoff(job, auto.workspaceId, auto.workspaceName);
  else job.handoff = {status: 'resolving', startedAt: Date.now(), message: '正在识别邀请这个邮箱的团队…'};
}

// Every pause keeps a fixed reason code and the step it stopped on: diagnostics show the cause,
// and a timeout pause can end by itself once the page reaches a later step.
function pauseJob(job, message, reason, {stage, page} = {}) {
  const at = STAGES.has(stage) ? stage : job.stage;
  recordEvent(job, 'paused', {page, stage: at, reason: pauseReason(reason)});
  job.status = 'paused'; job.message = message;
  job.pauseReason = pauseReason(reason); job.pausedStage = at; job.pausedAt = Date.now();
  delete job.reloadAt;
  if (autoRetryAllowed(job)) {
    const left = AUTO_RETRY_LIMIT - (job.autoRetries?.[at] || 0);
    job.message = `${message}窗口可见时约 ${AUTO_RETRY_DELAY / 1000} 秒后自动重试本步（还剩 ${left} 次）。`;
  }
}
// "Refresh and continue" resumes only from a document created after the refresh request.
const RELOAD_WAIT = 60000;

async function resumeJob(job, {auto = false, retry = false} = {}) {
  if (job.status !== 'paused') throw new Error('当前任务无法继续，请重新开始。');
  // Only a timed-out submission may be retried, and the total attempt limit remains in force.
  if (job.retryClaim) {
    delete job.claims[job.retryClaim];
    // If a page unloaded before acknowledging a click, its outcome is unknown.
    // Keep the attempt counted and don't reuse a code it may have submitted.
    const abandoned = job.clickReservations?.[job.retryClaim];
    if (abandoned?.code && job.pendingCode === abandoned.code) {
      job.ignoredCodes.push(job.pendingCode); delete job.pendingCode;
    }
    if (job.clickReservations) delete job.clickReservations[job.retryClaim];
    delete job.retryClaim;
  }
  job.status = 'running';
  // After "3 numbers failed" the user gets exactly one more number per Continue; the count is kept.
  if (job.pauseReason === 'phone_limit') job.phoneLimit = (job.phoneTries || 0) + 1;
  // The page never confirmed the typed SMS code: a manual Continue types it once more.
  if (!auto && !retry && job.phone?.codeSubmittedAt) delete job.phone.codeSubmittedAt;
  job.message = retry ? '网页已恢复显示，自动重试本步' : auto ? '网页已前进，自动继续本次注册' : '继续本次注册';
  if (retry) {
    job.autoRetries = {...job.autoRetries, [job.pausedStage]: (job.autoRetries?.[job.pausedStage] || 0) + 1};
  } else if (!auto) delete job.autoRetries; // the user looked at the page: allow fresh automatic retries
  const retriedStage = job.pausedStage;
  delete job.codeWaitSince; delete job.pauseReason; delete job.pausedStage; delete job.pausedAt; delete job.reloadAt;
  recordEvent(job, retry ? 'auto_retried' : auto ? 'auto_resumed' : 'resumed', {stage: retry ? retriedStage : job.stage});
  job.resumeCount = (job.resumeCount || 0) + 1;
  await saveJob(job);
  return {};
}

// The popup's Stop; server mode uses the same for the server's "stop" command.
function applyStop(job) {
  recordEvent(job, 'stopped');
  job.status = 'stopped'; job.message = '已停止。可手动继续网页操作。';
  delete job.baseline; delete job.pendingCode;
  releasePhone(job);
  if (HANDOFF_ACTIVE.has(job.handoff?.status) || job.handoff?.status === 'authorizing') failHandoff(job, '已停止接入。');
}

// Starts a signup in a new tab of the current incognito window (popup), or in a given tab
// of the server browser (server mode: runner = {workspaceNames}, fixed password, no handoff).
async function startJob({email: rawEmail, mode: rawMode, profile: rawProfile, hidePanel, handoff, tabId, password, runner: runnerTask = null}) {
  const server = !!RUNNER && !!runnerTask;
  if (!server && !chrome.extension.inIncognitoContext) throw new Error('请在无痕窗口里打开插件并开始注册。');
  const job = await expire(await loadJob());
  if (job && ACTIVE.has(job.status)) throw new Error('已有任务，请先停止当前注册。');
  if (HANDOFF_ACTIVE.has(job?.handoff?.status)) throw new Error('上一个账号仍在接入 Team48，请等待完成。');
  if (job?.handoff?.status === 'callback_retry') throw new Error('上一个账号的授权回调尚未提交，请先重新提交或清除。');
  const autoHandoff = server || !TEAM48 ? null : handoff?.auto === true ?
    {auto: true, workspaceId: null, workspaceName: '', resolve: {status: 'resolving', message: '正在识别团队…'}} :
    Number.isInteger(Number(handoff?.workspaceId)) && Number(handoff.workspaceId) > 0 ?
      {workspaceId: Number(handoff.workspaceId), workspaceName: String(handoff.workspaceName || '').slice(0, 120)} : null;
  const email = String(rawEmail || '').trim().toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || email.length > 254) throw new Error('邮箱格式不正确。');
  const mode = rawMode || 'auto';
  if (!MODES.has(mode)) throw new Error('注册模式无效。');
  const profile = checkedProfile(rawProfile);
  if (server && (typeof password !== 'string' || !password)) throw new Error('任务缺少密码。');
  let tab = null, windowId;
  if (Number.isInteger(tabId)) tab = await chrome.tabs.get(tabId);
  else {
    const window = await chrome.windows.getCurrent();
    if (!server && !window.incognito) throw new Error('当前窗口不是无痕窗口。');
    windowId = window.id;
  }
  const automaticFill = mode === 'auto' || mode === 'review';
  const baseline = automaticFill ? await startMailbox(MAIL, email) : null;
  if (!tab) tab = await chrome.tabs.create({windowId, url: 'about:blank', active: true});
  const current = {
    id: crypto.randomUUID(), tabId: tab.id, email, password: server ? password : newPassword(), profile: profile || defaultProfile(), baseline,
    hidePanel: automaticFill && hidePanel === true,
    mode, profileSource: automaticFill ? (profile ? 'custom' : 'generated') : 'manual', startedAt: Date.now(), events: [],
    status: 'running', stage: 'signup', message: '正在打开 ChatGPT 注册页面',
    expiresAt: Date.now() + (mode === 'auto' ? RUN_TTL : 30 * 60 * 1000),
    claims: {}, attempts: {}, ignoredCodes: [], lastPoll: 0, autoHandoff,
    ...(server ? {runner: {workspaceNames: runnerTask.workspaceNames || [], phonePool: runnerTask.phonePool === true}} : {}),
  };
  recordEvent(current, 'started');
  await saveJob(current);
  await chrome.alarms.create('signup-expiry', {when: current.expiresAt});
  try { await chrome.tabs.update(tab.id, {url: 'https://chatgpt.com/', ...(server ? {active: true} : {})}); }
  catch { current.status = 'stopped'; current.message = '注册标签页已关闭，请重新开始。'; delete current.baseline; await saveJob(current); }
  if (autoHandoff?.auto && current.status === 'running') prefetchTeam(current);
  return current;
}

async function popupMessage(message) {
  const job = await expire(await loadJob());
  if (message.type === 'view') {
    if (HANDOFF_ACTIVE.has(job?.handoff?.status)) ensureHandoff();
    return {job: publicJob(job), incognito: chrome.extension.inIncognitoContext, version: chrome.runtime.getManifest().version, team48: !!TEAM48};
  }
  if (message.type === 'start') {
    const current = await startJob({email: message.email, mode: message.mode, profile: message.profile,
      hidePanel: message.hidePanel, handoff: message.handoff});
    return {job: publicJob(current)};
  }
  if (message.type === 'clear') {
    if (job && ACTIVE.has(job.status)) throw new Error('请先停止当前注册。');
    if (HANDOFF_ACTIVE.has(job?.handoff?.status)) throw new Error('正在接入 Team48，请等待完成。');
    await chrome.storage.session.remove('job');
    return {};
  }
  if (!job) throw new Error('没有正在进行的注册。');
  if (message.type === 'handoff-start') {
    if (!TEAM48) throw new Error('插件未配置 Team48 地址和令牌。');
    if (HANDOFF_ACTIVE.has(job.handoff?.status) || ACTIVE.has(job.status)) throw new Error('授权进行中，请等待完成或先停止。');
    if (job.status !== 'done' && job.phase !== 'oauth') throw new Error('请在注册完成后再接入 Team48。');
    const workspaceId = Number(message.workspaceId);
    if (!Number.isInteger(workspaceId) || workspaceId <= 0) throw new Error('请选择团队。');
    beginHandoff(job, workspaceId, message.workspaceName);
    await saveJob(job);
    ensureHandoff();
    return {};
  }
  if (message.type === 'handoff-retry') {
    if (job.handoff?.status !== 'callback_retry') throw new Error('当前没有可重新提交的回调。');
    job.handoff.status = 'completing'; job.handoff.message = '正在重新提交回调';
    await saveJob(job);
    ensureHandoff();
    return {};
  }
  if (message.type === 'diagnostics') return {report: diagnosticReport(job, chrome.runtime.getManifest().version)};
  if (message.type === 'set-result') {
    if (job.status !== 'done' || !['unknown', 'no_phone', 'phone_required', 'failed'].includes(message.result)) throw new Error('请在注册完成后选择授权结果。');
    job.codexResult = message.result;
    await saveJob(job);
    return {};
  }
  if (message.type === 'pause') {
    if (job.status !== 'running') return {};
    pauseJob(job, '已手动暂停，点击继续即可恢复。', 'user');
    await saveJob(job);
    return {};
  }
  if (message.type === 'reload-resume') {
    if (job.status !== 'paused') throw new Error('只有暂停中的任务可以刷新后继续。');
    if (!['auto', 'review'].includes(job.mode || 'auto')) throw new Error('手工模式请自行刷新网页后点继续。');
    // Stay paused until the fresh page reports in: the old page must not act while it unloads.
    job.reloadAt = Date.now();
    job.message = '正在刷新网页，加载完成后自动继续；长时间没有反应请检查网页后点继续。';
    recordEvent(job, 'page_reload', {stage: job.stage});
    await saveJob(job);
    try { await chrome.tabs.reload(job.tabId); }
    catch {
      delete job.reloadAt; job.pauseReason = 'reload_failed';
      job.message = '注册标签页无法刷新，请手动刷新网页后点继续。';
      await saveJob(job);
      throw new Error(job.message);
    }
    return {};
  }
  if (message.type === 'stop') {
    applyStop(job);
    await saveJob(job);
    return {};
  }
  if (message.type === 'resume') {
    return resumeJob(job);
  }
  if (message.type === 'mark-complete') {
    // The user confirms the page is logged in when automatic detection could not.
    // OAuth still logs in with this job's email and Team48 checks the token email.
    if (!ACTIVE.has(job.status) || job.phase === 'oauth' || !job.entryFormSeen) throw new Error('当前注册任务无需手动确认。');
    finishSignup(job, undefined, 'manual_complete');
    await saveJob(job);
    if (HANDOFF_ACTIVE.has(job.handoff?.status)) ensureHandoff();
    return {};
  }
  throw new Error('未知操作。');
}

async function contentMessage(message, sender) {
  const job = await expire(await loadJob());
  if (!contentAllowed(sender, job, !RUNNER) || !job) return {active: false};
  if (message.type !== 'state' && message.jobId !== job.id) return {active: false};
  if (message.version !== chrome.runtime.getManifest().version) {
    return {active: false, id: job.id, email: job.email, status: 'paused', stage: job.stage,
      message: '页面仍在使用旧版注册脚本，请刷新本页后继续。'};
  }
  if (message.type === 'state') {
    const state = {active: job.status === 'running', id: job.id, email: job.email,
      status: job.status, message: job.message, stage: job.stage, mode: job.mode || 'auto', resumeCount: job.resumeCount || 0,
      hidePanel: job.hidePanel === true, entryFallbackUsed: !!job.entryFallbackUsed, entryFormSeen: !!job.entryFormSeen,
      phase: job.phase === 'oauth' ? 'oauth' : 'signup', passwordSet: !!job.passwordSet,
      workspaceNames: job.phase === 'oauth' ? job.handoff?.workspaceNames || [] : [],
      phoneRelay: phoneRelayEnabled(job),
      ...(job.status === 'paused' ? {pausedStage: job.pausedStage || job.stage, reloadAt: job.reloadAt || 0,
        autoResume: AUTO_RESUME_REASONS.has(job.pauseReason), autoRetry: autoRetryAllowed(job)} : {})};
    return state.active ? {...state, password: job.password, profile: job.profile, reviewSteps: job.reviewSteps || {},
      phoneBack: !!job.phoneBack, phone: job.phone ? {id: job.phone.id, tail: job.phone.tail, bound: job.phone.bound,
        submitted: !!job.phone.submittedAt, codeSubmitted: !!job.phone.codeSubmittedAt, snapshot: job.phone.snapshot || null,
        sinceSubmit: job.phone.submittedAt ? Date.now() - job.phone.submittedAt : null} : null} : state;
  }
  if (message.type === 'resume' && job.status === 'paused') {
    // Server mode: a final pause (e.g. the entry form pause) stays where it stopped.
    if (job.runner && runnerPauseFinal(job)) return {};
    return resumeJob(job);
  }
  if (message.type === 'auto-resume') {
    if (job.status !== 'paused') return {resumed: false};
    // Either the page reloaded after "refresh and continue", or it reached a later step by itself
    // after a pause that only meant "the page did not move in time". A user pause never qualifies.
    const reloaded = message.reload === true && job.reloadAt && Date.now() - job.reloadAt < RELOAD_WAIT;
    const advanced = AUTO_RESUME_REASONS.has(job.pauseReason) && laterStage(message.stage, job.pausedStage);
    if (!reloaded && !advanced) return {resumed: false};
    if (reloaded) job.stage = STAGES.has(message.stage) ? message.stage : job.stage;
    await resumeJob(job, {auto: true});
    return {resumed: true};
  }
  if (message.type === 'auto-retry') {
    // The content script counts only time the page was visible; this is a wall-clock floor.
    if (!autoRetryAllowed(job) || Date.now() - (job.pausedAt || 0) < AUTO_RETRY_DELAY) return {resumed: false};
    await resumeJob(job, {retry: true});
    return {resumed: true};
  }
  if (message.type === 'finish-click') {
    const url = new URL(sender.url), key = `${message.stage}:${url.pathname}`;
    const reserved = job.clickReservations?.[key];
    if (!reserved || reserved.token !== message.token || reserved.origin !== url.origin ||
        typeof message.sent !== 'boolean') return {accepted: false};
    delete job.clickReservations[key];
    if (!message.sent) {
      // Only release a reservation whose click was definitely never dispatched.
      delete job.claims[key];
      job.attempts[message.stage] = Math.max(0, (job.attempts[message.stage] || 0) - 1);
      if (reserved.retry) {
        if (reserved.previousClaim) job.claims[key] = reserved.previousClaim;
        job.continueRetries[message.stage] = Math.max(0, job.continueRetries[message.stage] - 1);
      }
    } else {
      if (reserved.code && job.pendingCode === reserved.code) {
        job.ignoredCodes.push(job.pendingCode); delete job.pendingCode;
      }
      recordEvent(job, 'submit_attempt', {page: pageKind(sender.url), stage: message.stage});
      if (['otp', 'profile'].includes(message.stage)) {
        job.continueClicks ||= {};
        job.continueClicks[key] = {token: reserved.token, origin: reserved.origin, at: Date.now(),
          blocked: job.continueClicks[key]?.blocked || false, left: job.continueClicks[key]?.left || false};
        if (reserved.retry) recordEvent(job, 'continue_retry', {page: pageKind(sender.url), stage: message.stage});
      }
    }
    await saveJob(job);
    return {accepted: true};
  }
  if (job.status !== 'running') return {active: false};
  if (message.type === 'continue-observed') {
    if (job.mode === 'manual' || !['otp', 'profile'].includes(message.stage)) return {granted: false};
    const url = new URL(sender.url), key = `${message.stage}:${url.pathname}`;
    if (job.clickReservations?.[key]) return {granted: false};
    job.continueClicks ||= {};
    const token = crypto.randomUUID();
    job.continueClicks[key] = {token, origin: url.origin, at: Date.now(), blocked: false};
    recordEvent(job, 'manual_submit', {page: pageKind(sender.url), stage: message.stage});
    await saveJob(job);
    return {granted: true, token};
  }
  if (message.type === 'retry-continue') {
    const url = new URL(sender.url), key = `${message.stage}:${url.pathname}`;
    const previous = job.continueClicks?.[key];
    // A stalled retry follows a spinner/submit that went idle on the same form; only a page change
    // (not the earlier loading response) rules it out.
    const stalled = message.stalled === true;
    if (job.mode === 'manual' || !['otp', 'profile'].includes(message.stage) || !previous ||
        (stalled ? previous.left : previous.blocked) ||
        previous.origin !== url.origin || previous.token !== message.token ||
        job.clickReservations?.[key]) return {granted: false};
    if ((job.continueRetries?.[message.stage] || 0) >= CONTINUE_RETRIES ||
        (job.attempts[message.stage] || 0) >= CONTINUE_RETRIES + 1) return {granted: false, limit: true};
    if (Date.now() - previous.at < 2000) return {granted: false, wait: true};
    // This is another click on the unchanged form, never a request for another OTP.
    const token = crypto.randomUUID();
    job.clickReservations ||= {};
    job.clickReservations[key] = {token, origin: url.origin, retry: true, previousClaim: job.claims[key],
      code: message.stage === 'otp' ? job.pendingCode : undefined};
    job.claims[key] = Date.now();
    job.attempts[message.stage] = (job.attempts[message.stage] || 0) + 1;
    job.continueRetries ||= {};
    job.continueRetries[message.stage] = (job.continueRetries[message.stage] || 0) + 1;
    await saveJob(job);
    return {granted: true, token};
  }
  if (message.type === 'entry-fallback') {
    const url = new URL(sender.url);
    if (url.origin !== 'https://chatgpt.com' || url.pathname !== '/' ||
        !['auto', 'review'].includes(job.mode || 'auto') || job.entryFallbackUsed || job.entryFormSeen ||
        Date.now() - job.startedAt < 15000 ||
        Object.keys(job.claims).some(key => !key.startsWith('signup:'))) return {granted: false};
    // Persist before navigating; reloads and worker restarts must not create a redirect loop.
    job.entryFallbackUsed = true;
    recordEvent(job, 'entry_fallback', {page: 'chatgpt', stage: 'signup'});
    job.message = '主页注册入口未响应，正在尝试备用入口。';
    await saveJob(job);
    return {granted: true, url: 'https://chatgpt.com/auth/login'};
  }
  if (message.type === 'review-ready' && job.mode === 'review' && STAGES.has(message.stage)) {
    // The user submits in review mode; the password we typed is still the account's password.
    if (message.stage === 'password' && job.phase !== 'oauth') job.passwordSet = true;
    job.reviewSteps ||= {};
    job.reviewSteps[`${message.stage}:${new URL(sender.url).pathname}`] = true;
    recordEvent(job, 'waiting_manual', {page: pageKind(sender.url), stage: message.stage});
    await saveJob(job);
    return {};
  }
  if (message.type === 'phone-number') {
    // phone: the number form asks for a number; phone_otp: a code form with no number this job submitted.
    if (!phoneRelayEnabled(job)) return {disabled: true};
    const bound = message.bound === true;
    const stage = bound ? 'phone_otp' : 'phone';
    let changed = job.stage !== stage;
    job.stage = stage;
    if (!bound && job.phoneBack) { delete job.phoneBack; changed = true; }
    if (job.phone) {
      if (changed) await saveJob(job);
      return phoneReply(job.phone);
    }
    if (bound && job.phoneBack) { if (changed) await saveJob(job); return {back: true}; }
    // Wait for a report still in flight: until it lands the server would hand out the same number again.
    if (phoneCalls > 0) { if (changed) await saveJob(job); return {wait: true}; }
    if ((job.phoneTries || 0) >= phoneLimit(job)) { phoneLimitPause(job); await saveJob(job); return {paused: true}; }
    job.message = bound ? '页面要求验证已绑定的手机号，正在向服务器取该号的短信' : `正在从号码池领取号码（第 ${(job.phoneTries || 0) + 1}/${phoneLimit(job)} 个）`;
    await saveJob(job);
    phoneCalls++;
    return {phoneCall: {...phoneContext(job), action: 'acquire', bound, failedIds: [...(job.phoneFailedIds || [])]}};
  }
  if (message.type === 'phone-submitted') {
    const phone = job.phone;
    if (!phone || phone.id !== Number(message.phoneId)) return {};
    if (message.step === 'code') {
      if (!phone.code || phone.codeSubmittedAt) return {};
      phone.codeSubmittedAt = Date.now(); job.message = '已输入短信验证码，等待页面确认';
    } else {
      if (phone.bound || phone.submittedAt) return {};
      phone.submittedAt = Date.now();
      recordEvent(job, 'phone_submitted', {page: pageKind(sender.url), stage: 'phone'});
      job.message = `已提交尾号 ${phone.tail} 的号码，等待短信验证码`;
    }
    await saveJob(job);
    return {};
  }
  if (message.type === 'phone-snapshot') {
    // What the page said when this number / code was submitted; survives a reload of the phone page.
    const phone = job.phone;
    if (!phone || phone.id !== Number(message.phoneId) || !['number', 'code'].includes(message.step)) return {};
    phone.snapshot = {step: message.step, outcome: String(message.outcome || '')};
    await saveJob(job);
    return {};
  }
  if (message.type === 'phone-code') {
    const phone = job.phone;
    if (!phoneRelayEnabled(job) || !phone) return {code: null, missing: true};
    let changed = job.stage !== 'phone_otp';
    job.stage = 'phone_otp';
    // Review mode: the person submitted the number; the timer starts once the code page shows.
    if (!phone.submittedAt) {
      phone.submittedAt = Date.now(); changed = true;
      recordEvent(job, 'phone_submitted', {page: pageKind(sender.url), stage: 'phone_otp'});
    }
    if (phone.code || phone.codeSubmittedAt) {
      if (changed) await saveJob(job);
      return {code: phone.codeSubmittedAt ? null : phone.code};
    }
    if (Date.now() - phone.submittedAt > SMS_WAIT) {
      failPhone(job, 'no_sms');
      await saveJob(job);
      return {code: null, rejected: true};
    }
    if (phoneCalls > 0 || Date.now() - (phone.lastPoll || 0) < SMS_POLL) { if (changed) await saveJob(job); return {code: null}; }
    phone.lastPoll = Date.now();
    job.message = `等待尾号 ${phone.tail} 的短信验证码（已等 ${Math.round((Date.now() - phone.submittedAt) / 1000)} 秒，最多 ${SMS_WAIT / 1000} 秒）`;
    await saveJob(job);
    phoneCalls++;
    return {phoneCall: {...phoneContext(job), action: 'code', phoneId: phone.id, bound: phone.bound}};
  }
  if (message.type === 'phone-result') {
    // The page rejected the number or the SMS code.
    if (!job.phone || job.phone.id !== Number(message.phoneId) ||
        !['invalid', 'recently_used', 'risk', 'wrong_code', 'cancelled'].includes(message.outcome)) return {};
    failPhone(job, message.outcome);
    await saveJob(job);
    return {};
  }
  if (message.type === 'event') {
    if (['page', 'filled', 'form_submit', 'manual_submit', 'waiting_manual', 'session_check', 'session_error', 'session_anonymous', 'captcha', 'phone', 'rate_limit', 'click_response', 'submit_stalled', 'control_wait'].includes(message.event) &&
        recordEvent(job, message.event, {page: pageKind(sender.url), stage: message.stage, verified: message.verified, outcome: message.outcome, control: message.control})) {
      if (message.event === 'page' && ['email', 'password', 'otp', 'profile'].includes(message.stage)) job.entryFormSeen = true;
      if (message.event === 'phone' && job.phase === 'oauth') job.codexResult = 'phone_required';
      // The SMS code was accepted: the page moved on to a later step (profile, consent, home).
      if (message.event === 'page' && pageKind(sender.url) !== 'phone' && !['phone', 'phone_otp'].includes(message.stage) &&
          (message.stage !== 'unknown' || ['consent', 'profile', 'chatgpt'].includes(pageKind(sender.url)))) phoneSucceeded(job);
      const key = `${message.stage}:${new URL(sender.url).pathname}`;
      if (message.event === 'click_response' && ['submitted', 'loading', 'advanced', 'validation'].includes(message.outcome) && job.continueClicks?.[key]) {
        job.continueClicks[key].blocked = true;
      }
      if (message.event === 'page') {
        for (const [receiptKey, receipt] of Object.entries(job.continueClicks || {})) {
          if (receiptKey !== key || receipt.origin !== new URL(sender.url).origin) { receipt.blocked = true; receipt.left = true; }
        }
      }
      await saveJob(job);
    }
    return {};
  }
  if (message.type === 'pause') {
    pauseJob(job, String(message.reason || '请手动处理页面后点击继续。').slice(0, 200), message.code,
      {stage: message.stage, page: pageKind(sender.url)});
    await saveJob(job);
    return {active: false};
  }
  if (message.type === 'complete') {
    if (new URL(sender.url).hostname !== 'chatgpt.com' || job.phase === 'oauth') return {active: false};
    if (String(message.email || '').toLowerCase() !== job.email) {
      recordEvent(job, 'email_mismatch');
      pauseJob(job, '当前登录邮箱不匹配，请关闭全部无痕窗口后重新开始。', 'email_mismatch', {stage: 'home'});
    } else if (message.verified === false) {
      job.emailVerified = false; recordEvent(job, 'email_unverified');
      pauseJob(job, '已登录，但会话报告邮箱尚未验证，请在网页完成验证后继续。', 'email_unverified', {stage: 'home'});
    } else finishSignup(job, message.verified, 'completed');
    await saveJob(job);
    if (HANDOFF_ACTIVE.has(job.handoff?.status)) ensureHandoff();
    return {};
  }
  if (message.type === 'claim') {
    const limits = {signup: 3, email: 2, password: 2, profile: 2, otp: 2, consent: 4, phone: 2, phone_otp: 2};
    if (!Object.hasOwn(limits, message.stage)) throw new Error('不支持的注册步骤。');
    if (job.mode === 'manual' || (job.mode === 'review' && !message.prepare && message.stage !== 'signup')) return {granted: false};
    const key = `${message.stage}:${new URL(sender.url).pathname}`;
    if (job.claims[key]) {
      if (Date.now() - job.claims[key] > 45000) {
        pauseJob(job, '提交后页面没有前进，请检查网页提示后点击继续重试。', 'claim_timeout', {stage: message.stage, page: pageKind(sender.url)});
        job.retryClaim = key;
        await saveJob(job);
      }
      return {granted: false};
    }
    if ((job.attempts[message.stage] || 0) >= limits[message.stage]) {
      pauseJob(job, '已达到自动提交次数，请检查页面并手动继续。', 'attempt_limit', {stage: message.stage, page: pageKind(sender.url)});
      await saveJob(job); return {granted: false};
    }
    if (message.prepare) return {granted: true};
    if (!message.reserve && message.stage === 'otp' && job.pendingCode) {
      job.ignoredCodes.push(job.pendingCode);
      delete job.pendingCode;
    }
    job.stage = message.stage;
    if (message.stage === 'password' && job.phase !== 'oauth') job.passwordSet = true;
    if (!message.reserve) recordEvent(job, 'submit_attempt', {page: pageKind(sender.url), stage: message.stage});
    job.claims[key] = Date.now();
    job.attempts[message.stage] = (job.attempts[message.stage] || 0) + 1;
    job.message = job.phase === 'oauth' ?
      {email: '提交登录邮箱', password: '输入登录密码', profile: '填写个人资料', otp: '提交登录验证码', consent: '确认授权',
        phone: '提交手机号', phone_otp: '提交短信验证码'}[message.stage] || '正在授权' :
      {signup: '打开邮箱注册', email: '提交邮箱', password: '设置注册密码', profile: '填写个人资料', otp: '提交邮箱验证码',
        phone: '提交手机号', phone_otp: '提交短信验证码'}[message.stage];
    const token = message.reserve ? crypto.randomUUID() : undefined;
    if (message.reserve) {
      job.clickReservations ||= {};
      job.clickReservations[key] = {token, origin: new URL(sender.url).origin,
        code: message.stage === 'otp' ? job.pendingCode : undefined};
    }
    await saveJob(job); return {granted: true, ...(token ? {token} : {})};
  }
  if (message.type === 'code') {
    if (job.mode === 'manual' || job.mode === 'submit' || !job.baseline) return {code: null};
    // Never an email code on a phone page: its code comes by SMS (phone-code).
    if (pageKind(sender.url) === 'phone') return {code: null};
    const submitted = job.claims[`otp:${new URL(sender.url).pathname}`];
    if (submitted) {
      if (Date.now() - submitted > 45000) {
        pauseJob(job, '验证码提交后页面没有前进，请检查页面，必要时重发验证码后继续。', 'otp_submit_timeout', {stage: 'otp', page: pageKind(sender.url)});
        job.retryClaim = `otp:${new URL(sender.url).pathname}`;
        await saveJob(job);
      }
      return {code: null};
    }
    if (job.pendingCode) return {code: job.pendingCode};
    if (mailPolling || Date.now() - job.lastPoll < 4000) return {code: null};
    job.codeWaitSince ||= Date.now();
    if (Date.now() - job.codeWaitSince > OTP_WAIT) {
      delete job.codeWaitSince;
      pauseJob(job, `${OTP_WAIT / 1000} 秒内没有收到新的邮箱验证码。请在网页点「重新发送邮件」，再点击继续。`, 'otp_wait',
        {stage: 'otp', page: pageKind(sender.url)});
      await saveJob(job);
      return {code: null};
    }
    job.stage = 'otp';
    job.lastPoll = Date.now(); job.message = `等待 ${MAIL_NAME} 收到新的邮箱验证码`;
    await saveJob(job);
    // The mailbox request can take up to 25 s; run it outside the job queue (see finishCodePoll).
    mailPolling = true;
    return {mailPoll: {id: job.id, email: job.email, baseline: job.baseline, ignored: [...job.ignoredCodes]}};
  }
  return {active: false};
}

// Reading the mailbox used to hold the job queue, so page state, popup and pause
// requests all froze until Cloudflare answered. Only the result is stored under the queue.
const OTP_WAIT = 120000;
// Extra Continue clicks per OTP/profile step when the unchanged page does not advance.
const CONTINUE_RETRIES = 3;
let mailPolling = false;
async function finishCodePoll({id, email, baseline, ignored}) {
  let code;
  try { code = await pollMailbox(MAIL, email, baseline, ignored); }
  finally { mailPolling = false; }
  if (!code) return {code: null};
  if (!/^\d{6}$/.test(code)) throw new Error('邮箱验证码格式异常，请手动检查。');
  return serial(async () => {
    const job = await loadJob();
    // Paused, stopped or replaced while reading: the next poll finds the same mail again.
    if (!job || job.id !== id || job.status !== 'running' || !job.baseline || job.ignoredCodes.includes(code)) return {code: null};
    if (job.pendingCode) return {code: job.pendingCode};
    job.pendingCode = code; delete job.codeWaitSince;
    recordEvent(job, 'code_received', {stage: 'otp'});
    job.message = '已收到验证码，正在逐位输入';
    await saveJob(job);
    return {code};
  });
}

let inputQueue = Promise.resolve();
const inputSerial = task => {
  const next = inputQueue.then(task);
  inputQueue = next.catch(() => {});
  return next;
};
chrome.runtime.onMessage.addListener((message, sender, respond) => {
  const fromPopup = sender.url === chrome.runtime.getURL('popup.html');
  // Key/mouse commands only read the job; keep them off the queue a mailbox poll may hold.
  const input = !fromPopup && /^input-(move|click|key|text|wheel|drift|date-layout)$/.test(message?.type);
  if (fromPopup && message?.type === 'workspaces') {
    // A slow Team48 request must not hold the job queue.
    (async () => {
      if (sender.id !== chrome.runtime.id) throw new Error('来源无效。');
      const payload = await team48('/api/ext/workspaces');
      return {items: (payload.items || []).map(item => ({id: Number(item.id), name: String(item.name || `团队 ${item.id}`)}))};
    })().then(data => respond({ok: true, ...data}), error => respond({ok: false, error: error.message}));
    return true;
  }
  (input ? inputSerial : serial)(async () => {
    await ready;
    if (sender.id !== chrome.runtime.id) throw new Error('来源无效。');
    if (fromPopup) return popupMessage(message);
    return input || message?.type === 'input-ready' ? inputMessage(message, sender) : contentMessage(message, sender);
  }).then(data => data?.mailPoll ? finishCodePoll(data.mailPoll) : data?.phoneCall ? finishPhoneCall(data.phoneCall) : data)
    .then(data => respond({ok: true, ...data}), error => respond({ok: false, error: error.message}));
  return true;
});
chrome.debugger?.onDetach.addListener(({tabId}, reason) => {
  debuggerTabs.delete(tabId); pointers.delete(tabId);
  if (reason !== 'canceled_by_user') return;
  serial(async () => {
    const job = await loadJob();
    if (job?.tabId === tabId && job.status === 'running') {
      pauseJob(job, '调试连接被取消，已暂停；点击继续会重新连接。', 'debugger_detached');
      await saveJob(job);
    }
  });
});
chrome.alarms.onAlarm.addListener(alarm => {
  if (alarm.name === 'signup-expiry') serial(async () => expire(await loadJob()));
  if (alarm.name === 'handoff-watchdog') ensureHandoff();
  if (alarm.name === RUNNER_ALARM) runner?.boot();
});
chrome.tabs.onRemoved.addListener(tabId => {
  serial(async () => {
    const job = await loadJob();
    if (job?.tabId === tabId && ACTIVE.has(job.status)) {
      recordEvent(job, 'stopped');
      job.status = 'stopped'; job.message = job.phase === 'oauth' ? '授权标签页已关闭。' : '注册标签页已关闭。';
      delete job.baseline; delete job.pendingCode;
      releasePhone(job);
      if (job.handoff?.status === 'authorizing') failHandoff(job, '授权标签页已关闭，可重新接入。');
      await saveJob(job);
    }
  });
});
// The OAuth redirect goes to the Codex CLI loopback address, where nothing needs to listen.
const CALLBACK_FILTER = {url: [{hostEquals: 'localhost', ports: [1455], pathEquals: '/auth/callback'},
  {hostEquals: '127.0.0.1', ports: [1455], pathEquals: '/auth/callback'}]};
for (const name of ['onBeforeNavigate', 'onCommitted', 'onErrorOccurred']) {
  chrome.webNavigation?.[name]?.addListener(details => { if (details.frameId === 0) captureCallback(details.tabId, details.url); }, CALLBACK_FILTER);
}
chrome.tabs.onUpdated?.addListener((tabId, change) => { if (change.url) captureCallback(tabId, change.url); });

// ---- Server mode (only with a valid RUNNER export; see runner.mjs) ----
// The server browser opens about:blank in a normal window of a fresh, dedicated profile.
async function pickRunnerTab() {
  const windows = await chrome.windows.getAll({populate: true, windowTypes: ['normal']});
  const window = windows.find(item => !item.incognito && item.tabs?.length);
  return window?.tabs.find(item => item.active) || window?.tabs[0] || chrome.tabs.create({url: 'about:blank', active: true});
}
if (RUNNER) {
  runner = createRunner(RUNNER, {
    ready,
    version: () => chrome.runtime.getManifest().version,
    pickTab: pickRunnerTab,
    loadJob,
    startJob: ({email, password, profile, workspaceNames, phonePool}) => serial(async () => {
      const tab = await pickRunnerTab();
      await startJob({email, mode: 'auto', profile, hidePanel: true, handoff: null, tabId: tab.id, password,
        runner: {workspaceNames, phonePool: phonePool === true}});
    }),
    stopJob: () => serial(async () => {
      const job = await loadJob();
      if (!job?.runner || job.status === 'stopped' || job.handoff?.status === 'done') return;
      applyStop(job);
      await saveJob(job);
    }),
    // Opens the server's authorization link in the signup tab; a repeated link is ignored.
    // url === null resumes an "opening" step interrupted by a worker restart.
    authorize: async url => {
      const id = await serial(async () => {
        const job = await loadJob();
        if (!job?.runner) return null;
        if (url && !job.handoff && job.status === 'done' && job.phase !== 'oauth') {
          const names = job.runner.workspaceNames || [];
          job.handoff = {status: 'opening', authorizeUrl: url, workspaceNames: names, workspaceName: String(names[0] || '').slice(0, 120),
            startedAt: Date.now(), message: '已收到授权链接，正在打开授权页面'};
          await saveJob(job);
        }
        return job.handoff?.status === 'opening' ? job.id : null;
      });
      if (id) await openAuthorization(id);
    },
    callbackResult: (ok, message) => serial(async () => {
      const job = await loadJob();
      if (!job?.runner || job.handoff?.status !== 'completing') return;
      if (ok) {
        Object.assign(job.handoff, {status: 'done', message: '授权回调已交给服务器'});
        delete job.handoff.authorizeUrl; delete job.handoff.callbackUrl;
        if (job.codexResult !== 'phone_required') job.codexResult = 'no_phone';
        job.message = '已把授权回调交给服务器。';
      } else failHandoff(job, message);
      await saveJob(job);
    }),
  });
  chrome.runtime.onStartup.addListener(() => { runner.boot(); });
  chrome.runtime.onInstalled.addListener(() => { runner.boot(); });
  // Also on every worker start, so a suspended worker resumes reporting right away.
  runner.boot();
}
